package vistas;

import java.awt.Color;

public class RegistroAbono extends javax.swing.JFrame {

    public RegistroAbono() {
        initComponents();
        //////////DISEÑO: COLORES SALDO POSITIVO Y NEGATIVO/////////
        int saldo = Integer.parseInt(this.tfsaldoactual.getText());
        if(Integer.parseInt(this.tfsaldoactual.getText())<0) {            
            this.tfsaldoactual.setBackground(new Color(255,0,0));            
            this.tfsaldoactual.setText("$"+saldo);
        }
        else {
            this.tfsaldoactual.setBackground(new Color(0,210,0));
            this.tfsaldoactual.setText("$"+saldo);
        }
        /////////////////////////////////////////////////////////////
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfusuario = new javax.swing.JTextField();
        tffechausuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbautomovil = new javax.swing.JButton();
        jbabono = new javax.swing.JButton();
        jbpropietario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tffecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfhora = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        tfdni = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        tfapellido = new javax.swing.JTextField();
        tfnombre = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        tfingresarimporte = new javax.swing.JTextField();
        tfsaldoactual = new javax.swing.JTextField();
        jbguardar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 227, 59));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        tfusuario.setFont(new java.awt.Font("Quicksand", 1, 23)); // NOI18N
        tfusuario.setForeground(new java.awt.Color(255, 255, 255));
        tfusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfusuario.setText("USER_MAJO");
        tfusuario.setBorder(null);
        tfusuario.setFocusable(false);
        tfusuario.setOpaque(false);
        jPanel2.add(tfusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 163, -1, -1));

        tffechausuario.setFont(new java.awt.Font("Quicksand", 0, 15)); // NOI18N
        tffechausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tffechausuario.setText("28/06/2018");
        tffechausuario.setBorder(null);
        tffechausuario.setFocusable(false);
        tffechausuario.setOpaque(false);
        jPanel2.add(tffechausuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 195, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fecha_user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 197, -1, -1));

        jbautomovil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_automovil_off.png"))); // NOI18N
        jbautomovil.setBorder(null);
        jbautomovil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbautomovil.setOpaque(false);
        jbautomovil.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_automovil_on.png"))); // NOI18N
        jbautomovil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_automovil_on.png"))); // NOI18N
        jbautomovil.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_automovil_on.png"))); // NOI18N
        jPanel2.add(jbautomovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 420, -1, -1));

        jbabono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_abono_off.png"))); // NOI18N
        jbabono.setBorder(null);
        jbabono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbabono.setOpaque(false);
        jbabono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_abono_on.png"))); // NOI18N
        jbabono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_abono_on.png"))); // NOI18N
        jbabono.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_abono_on.png"))); // NOI18N
        jbabono.setSelected(true);
        jbabono.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_abono_on.png"))); // NOI18N
        jPanel2.add(jbabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 300, -1, -1));

        jbpropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_propietario_off.png"))); // NOI18N
        jbpropietario.setBorder(null);
        jbpropietario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbpropietario.setOpaque(false);
        jbpropietario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_propietario_on.png"))); // NOI18N
        jbpropietario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_propietario_on.png"))); // NOI18N
        jbpropietario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_propietario_on.png"))); // NOI18N
        jPanel2.add(jbpropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 360, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 582, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barra.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_titulo.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 88, -1, -1));

        jLabel6.setFont(new java.awt.Font("Quicksand", 1, 23)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("<html>COBRO DE ABONO DE ESTACIONAMIENTO</html>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 280, 50));

        jSeparator1.setForeground(new java.awt.Color(255, 227, 59));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 166, 369, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 227, 59));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fecha.png"))); // NOI18N
        jLabel8.setText("FECHA ACTUAL:");
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 190, -1, -1));

        tffecha.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        tffecha.setForeground(new java.awt.Color(178, 178, 178));
        tffecha.setText("28/06/2018");
        tffecha.setBorder(null);
        jPanel1.add(tffecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 227, 59));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hora.png"))); // NOI18N
        jLabel9.setText("HORA ACTUAL:");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 215, -1, -1));

        jTextField2.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(178, 178, 178));
        jTextField2.setText("DNI:");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 340, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 227, 59));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 256, 228, 1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea_vertical.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 227, 59));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/persona.png"))); // NOI18N
        jLabel11.setText("BUSCAR PERSONA:");
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 310, -1, -1));

        tfhora.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        tfhora.setForeground(new java.awt.Color(178, 178, 178));
        tfhora.setText("22:50:02");
        tfhora.setBorder(null);
        jPanel1.add(tfhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 215, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(178, 178, 178));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 360, 90, 5));

        tfdni.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        tfdni.setForeground(new java.awt.Color(178, 178, 178));
        tfdni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfdni.setText("40123123");
        tfdni.setBorder(null);
        jPanel1.add(tfdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 340, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea_vertical2.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 408, -1, -1));

        jLabel15.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 227, 59));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/propietario.png"))); // NOI18N
        jLabel15.setText("PROPIETARIO:");
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 410, -1, -1));

        jTextField5.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(178, 178, 178));
        jTextField5.setText("APELLIDO:");
        jTextField5.setBorder(null);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 440, -1, -1));

        tfapellido.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        tfapellido.setForeground(new java.awt.Color(178, 178, 178));
        tfapellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfapellido.setText("Ceballe");
        tfapellido.setBorder(null);
        jPanel1.add(tfapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 440, 90, -1));

        tfnombre.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        tfnombre.setForeground(new java.awt.Color(178, 178, 178));
        tfnombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfnombre.setText("María José");
        tfnombre.setBorder(null);
        jPanel1.add(tfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 90, -1));

        jTextField8.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(178, 178, 178));
        jTextField8.setText("NOMBRE:");
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 460, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea_vertical3.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 408, -1, -1));

        jLabel17.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 227, 59));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saldo.png"))); // NOI18N
        jLabel17.setText("ESTADO DE CUENTA:");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 410, -1, -1));

        jTextField9.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(178, 178, 178));
        jTextField9.setText("SALDO ACTUAL:");
        jTextField9.setBorder(null);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 440, -1, -1));

        jTextField10.setFont(new java.awt.Font("Quicksand", 0, 16)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(178, 178, 178));
        jTextField10.setText("INGRESAR IMPORTE:");
        jTextField10.setBorder(null);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 465, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(178, 178, 178));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 487, 70, 5));

        tfingresarimporte.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        tfingresarimporte.setForeground(new java.awt.Color(178, 178, 178));
        tfingresarimporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfingresarimporte.setText("$300");
        tfingresarimporte.setBorder(null);
        jPanel1.add(tfingresarimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 465, 70, -1));

        tfsaldoactual.setFont(new java.awt.Font("Quicksand", 1, 16)); // NOI18N
        tfsaldoactual.setForeground(new java.awt.Color(255, 255, 255));
        tfsaldoactual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfsaldoactual.setText("5");
        tfsaldoactual.setBorder(null);
        jPanel1.add(tfsaldoactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 60, -1));

        jbguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_guardar_off.png"))); // NOI18N
        jbguardar.setBorder(null);
        jbguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbguardar.setOpaque(false);
        jbguardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_guardar_on.png"))); // NOI18N
        jbguardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_guardar_on.png"))); // NOI18N
        jbguardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_guardar_on.png"))); // NOI18N
        jPanel1.add(jbguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_cancelar_off.png"))); // NOI18N
        jbcancelar.setBorder(null);
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setOpaque(false);
        jbcancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_cancelar_on.png"))); // NOI18N
        jbcancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_cancelar_on.png"))); // NOI18N
        jbcancelar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_cancelar_on.png"))); // NOI18N
        jPanel1.add(jbcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_on.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_on.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_on.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAbono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbabono;
    private javax.swing.JButton jbautomovil;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbpropietario;
    private javax.swing.JTextField tfapellido;
    private javax.swing.JTextField tfdni;
    private javax.swing.JTextField tffecha;
    private javax.swing.JTextField tffechausuario;
    private javax.swing.JTextField tfhora;
    private javax.swing.JTextField tfingresarimporte;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfsaldoactual;
    private javax.swing.JTextField tfusuario;
    // End of variables declaration//GEN-END:variables
}
